

# This file was *autogenerated* from the file /mnt/d/Bureau/Arthur/github/Discord_CTFD/utils/Facto4CTF/modules/factoring/sage/ecm2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#!/usr/bin/env sage

import sys

try:
    print(ecm.factor(int(sys.argv[_sage_const_1 ]))[_sage_const_0 ])    
except:
    print(_sage_const_1 )

